Interface : Interface.o TrajetCompose.o TrajetSimple.o Trajet.o Element.o LinkedList.o Catalogue.o
	g++ -o Interface Interface.o TrajetCompose.o TrajetSimple.o Trajet.o Element.o LinkedList.o Catalogue.o
	
Trajet.o : Trajet.cpp
	g++ -c -g Trajet.cpp -ansi -pedantic -Wall -std=c++11

TrajetSimple.o : TrajetSimple.cpp
	g++ -c -g TrajetSimple.cpp -ansi -pedantic -Wall -std=c++11

TrajetCompose.o : TrajetCompose.cpp
	g++ -c -g TrajetCompose.cpp -ansi -pedantic -Wall -std=c++11
	
Interface.o : Interface.cpp
	g++ -c -g Interface.cpp -ansi -pedantic -Wall -std=c++11

Element.o : Element.cpp
	g++ -c -g Element.cpp -ansi -pedantic -Wall -std=c++11

LinkedList.o : LinkedList.cpp
	g++ -c -g LinkedList.cpp -ansi -pedantic -Wall -std=c++11

Catalogue.o : Catalogue.cpp
	g++ -c -g Catalogue.cpp -ansi -pedantic -Wall -std=c++11
