Interface : Interface.o TrajetSimple.o Trajet.o
	g++ -o Interface Interface.o TrajetSimple.o Trajet.o
	
Trajet.o : Trajet.cpp
	g++ -c Trajet.cpp -ansi -pedantic -Wall -std=c++11

TrajetSimple.o : TrajetSimple.cpp
	g++ -c TrajetSimple.cpp -ansi -pedantic -Wall -std=c++11
	
Interface.o : Interface.cpp
	g++ -c Interface.cpp -ansi -pedantic -Wall -std=c++11
